### ISSUE TITLE
border radius does not fit

### ISSUE THREAD

**Issue by rumpelsepp** [makotokw/redmine-theme-gitmike#16]
There is a problem with the border radius of the green box. It does not fit with radius of the grey line (there is some white space between).

Moreover I think the green box's border overlaps with the blue box.

![bildschirmfoto vom 2014-02-09 21 34 55](https://f.cloud.github.com/assets/1961699/2120898/b23f2f62-91c9-11e3-9d59-7fa0263ecd33.png)

**Comment by makotokw** [comment]
Adjusted in current version
