### ISSUE TITLE
[Question] why are some issues highlight red

### ISSUE THREAD

**Issue by faridskyman** [makotokw/redmine-theme-gitmike#24]
Hi,
im using redmine version: Redmine 2.6.1.stable
When i enable 'gitMike' theme, and i start browsing issues in project i notice that for a couple of 'issues',
the entire row background color for the issue becomes 'Red' and the Text formatting for the issue is 'Bold'

My Question is: "why is this happening", i checked due date, last update, etc, and cant seems to figure out the actual combination to cause this to happen.

Wondering if anyone could explain it.
![sales enhancement meeting](https://cloud.githubusercontent.com/assets/2541992/6590368/b0233bcc-c7e9-11e4-97df-ceddd1b8f447.jpg)

**Comment by makotokw** [comment]
It depends on issues's priority only.

**Comment by faridskyman** [comment]
hi makotokw
thanks, overlooked checking that item,
