### ISSUE TITLE
"New menu item" from Redmine 3.3 is not supported

### ISSUE THREAD

**Issue by schlamar** [makotokw/redmine-theme-gitmike#26]
Redmine 3.3 introduces a "new menu item" which is not properly supported by this theme: http://www.redmine.org/projects/redmine/news#New-menu-item-for-creating-objects-issues-wiki-pages-and-more

**Comment by bviktor** [comment]
Screenshot:

http://i.imgur.com/m3F05ym.png

**Comment by makotokw** [comment]
Thanks you for your report.
I have fixed in 1.0.8.

> There's space between the underline of all tabs and the container edge
I added other issue #27

**Comment by schlamar** [comment]
@makotokw Thanks. However, the default theme places the menu better. The menu starts at the bottom of the tabs and not at the beginning of the tabs:

![1](https://cloud.githubusercontent.com/assets/238652/16293326/598508ca-3919-11e6-9e33-19b30285d7dc.png)
![2](https://cloud.githubusercontent.com/assets/238652/16293337/6e6dff80-3919-11e6-8b93-d5c6b1845e11.png)

**Comment by makotokw** [comment]
I fixed in v1.0.9.

**Comment by bviktor** [comment]
Awesome, thank you !
