### ISSUE TITLE
No z-index set for new project menu

### ISSUE THREAD

**Issue by octoquad** [makotokw/redmine-theme-gitmike#31]
I just upgraded Redmine to 3.3.0 and updated your theme.

In firefox, the new menu (+) options are hidden underneath the page title.

The fix is to add z-index: 11 to #main-menu ul .menu-children {}

**Comment by makotokw** [comment]
Could you please attach a screenshot?
I don't know where is the issue in Redmine 3.3.1 wth gitmike 1.0.9 in Firefox 49.0.1.

**Comment by Addow** [comment]
Same for me, z-index of the new Redmine 3.3 menu is default 1 in latest gfm-css version. Increasing the z-index to a value higher than 10 fixes the problem. Screenshots before and after are attached.

### Before (z-index: 1)

![screen shot 2016-10-21 at 08 33 37](https://cloud.githubusercontent.com/assets/310765/19589218/44525362-976b-11e6-9727-9f56540c15db.png)

### After (z-index: 11)

![screen shot 2016-10-21 at 08 34 12](https://cloud.githubusercontent.com/assets/310765/19589217/445002a6-976b-11e6-8c0a-c27a180db678.png)

**Comment by octoquad** [comment]
@addow thanks for posting screenshots, I haven't had much time to do it myself. :)

**Comment by makotokw** [comment]
I can't reproduce it in both Redmine 3.3.0 and 3.3.1. Basically, this theme has never changed z-index.  

Please check that other theme work fine? If other theme is broken also, please let me know what plugin installed to change the menu or layout.

**Comment by addow** [comment]
@octoquad no problemo!

It's very strange you can 't reproduce it.

The first, the best custom theme I checked, PurpleMine2, also changed the [z-index](https://github.com/mrliptontea/PurpleMine2/blob/a72cf5a9ee320336337a13ac238f6a5adf266c84/src/sass/components/_top.scss#L334). Maybe you can adjust the value accordingly. I send a pull request with a z-index of 11, which will do for now. 99 is future safe ;-)

I ran some tests and can reproduce it on both Firefox & Chrome (latest versions).

**Comment by makotokw** [comment]
I wonder it is the issue of redmine.
http://www.redmine.org/issues/24000

**Comment by makotokw** [comment]
I picked setting z-index up in a stylesheet of redmine.

|selector|z-index|
|:--|:--|
|#main-menu .menu-children|1|
|#sidebar|9|
|#content|10|
|div.modal|50|
|#ajax-indicator|100|
|.tooltip|24|
|.tooltip:hover|25|

**Comment by addow** [comment]
Good point. If I switch theme to redmine default, the submenu is also hidden and I have to overwrite the z-index. So they should be able to reproduce it in redmine. I am watching that issue too, thanks for noticing.

**Comment by yeah** [comment]
Please see http://www.redmine.org/issues/24000#note-4. Could somebody try the Redmine patch and see if it's still reproducible?

**Comment by addow** [comment]
Works like a charm and future proof! Thanks, yeah! Looking forward to the next redmine minor release. Until then, I'll use this temporary z-index fix in gitmike only ;)

**Comment by makotokw** [comment]
I also updated to set 45 to z-index of menu-children in gitmike v1.1.0 until next release of Redmine.
