### ISSUE TITLE
Products menu item colorised (red) in project menu without hovering or selecting it

### ISSUE THREAD

**Issue by addow** [makotokw/redmine-theme-gitmike#32]
Products (RedmineCRM) menu item is highlighted in #F4786A without hovering or selecting the menu item.
Some leftovers in [sass/_store.scss](https://github.com/makotokw/redmine-theme-gitmike/blob/feature/gfm-css/sass/_store.scss#L1-L8) maybe?

### Before
![screen shot 2016-10-21 at 09 15 10](https://cloud.githubusercontent.com/assets/310765/19589861/0ab52676-976f-11e6-91ca-3f448cf87da0.png)

### After
![screen shot 2016-10-21 at 09 15 44](https://cloud.githubusercontent.com/assets/310765/19589862/0ae349f2-976f-11e6-8a6c-49bb1dd69db8.png)

**Comment by makotokw** [comment]
Thank you for you PR. I merged it. #34
