### ISSUE TITLE
Visual glitches on Redmine 3.4.0-devel

### ISSUE THREAD

**Issue by bviktor** [makotokw/redmine-theme-gitmike#36]
The projects page is seriously off, columns are way too narrow and there's a big empty space under them.

I can provide screenshots if needed. Thanks a lot.

**Comment by kacchan822** [comment]
I have also problem on Redmine 3.4.1.

**Comment by kzalewski** [comment]
The Projects page display issue is easily resolved by commenting out the two media queries in application.css that apply to the #projects-index selector.

The two offending lines are line 254 and line 256.  I simply moved the two lines to the bottom of that block, then commented them out.

Hopefully, the Makoto will take a moment to make this simple change to his code.
