### ISSUE TITLE
compatibility with select_to_select2 plugin

### ISSUE THREAD

**Issue by ilkosta** [makotokw/redmine-theme-gitmike#42]
Hello,
I'm trying the plugin https://github.com/sf-cola/select_to_select2 with the gitmike theme.

Editing an issue, at the beginning all looks good, but when i change the priority or assigned select, the width of all select go to 1px.

**Comment by makotokw** [comment]
select2/select2#4176

**Comment by makotokw** [comment]
After removing certain style, it did not reproduce in my development environment. Please confirm fixed from master branch.

**Comment by ilkosta** [comment]
perfect. It work. 
This will allow the use of custom fields otherwise impossible. 
thanks so much for everything

**Comment by ilkosta** [comment]
Hi,
a user has just told me that with the browser internet explorer, when it modify a ticket, the select of `project`, `author` `tracker` are poorly sized. 
The others are good.
With chrome and Firefox is all good.

**Comment by makotokw** [comment]
I could reproduce with default theme in IE11. Currently, I have no idea to find a workaround.

**Comment by makotokw** [comment]
I have not time to fix for IE11. I want user use Microsoft Edge.
