### ISSUE TITLE
Huge 300px area of whitespace in content area

### ISSUE THREAD

**Issue by kzalewski** [makotokw/redmine-theme-gitmike#43]
The issue list is severely compressed in Redmine 4.1.1, due to a 300px margin to the right of the issue list.  I'm not sure why that is there, but it should be removed.

https://github.com/makotokw/redmine-theme-gitmike/blob/94378c5f739454b20bc7b440b36747b28d76f371/stylesheets/application.css#L39

**Comment by makotokw** [comment]
I don't remember why it is required. I removed this style in v1.2.1.
It may require in old Redmine version but I have not test in old Redmine versions because I use Redmine 4.2.0.
