### ISSUE TITLE
Title bar background color on div content h2 does not fill out the whole line

### ISSUE THREAD

**Issue by MattMuffin** [makotokw/redmine-theme-gitmike#44]
On the issue view, the "title" bar is not colored; only the part with the title/issue name has the background color #E6F1F6

The issue seems to occur because of the presence of the span badge with the display: inline-inflex property setting.

**Comment by makotokw** [comment]
I don't know where is the problem. Please take me a screenshot.

**Comment by makotokw** [comment]
I found it and will fix in next version.

**Comment by makotokw** [comment]
v1.2.1 removed `background-color` with `.inline-flex`.
