### ISSUE TITLE
 Redmine 5.1.3 compatibility

### ISSUE THREAD

**Issue by hawk2012** [makotokw/redmine-theme-gitmike#49]
Hi! I saw the topic with this theme on the page https://github.com/alexandermeindl/awesome-redmine?tab=readme-ov-file#themes and couldn't get past it. For some reason, she is listed as inactive there, although she fit perfectly on Redmine 5.1.3. In this regard, a question arose about its compatibility.

**Comment by makotokw** [comment]
I have not yet been able to update to Redmine 5 due to a problem with some plugins I am using and therefore have not yet confirmed compatibility.

**Comment by hawk2012** [comment]
OK, thanks
